### PR TITLE
Update to version 0.16.0

### PR DESCRIPTION
**Pull request by m-rossi**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

I maintain the https://github.com/conda-forge/esptool-feedstock which depends on `ecdsa` and realized this recipe is outdated and I just updated it.

I can help maintain this feedstock in the future if you want.

### CODE REVIEW

**Comment by m-rossi** [comment]
@conda-forge-admin, please rerender

**Comment by m-rossi** [comment]
Ping @mariusvniekerk

**Comment by m-rossi** [comment]
Ping @conda-forge/core

We need this PR to be merged to complete this PR: https://github.com/conda-forge/esptool-feedstock/pull/4

**Comment by isuruf** [comment]
Please add yourself as a maintainer

**Comment by m-rossi** [comment]
@conda-forge-admin, please rerender

**Comment by isuruf** [comment]
Once the lint is fixed, please ping me

**Comment by m-rossi** [comment]
@isuruf recipe lint is fine and tests passed

**Pull request merged**
